FROM adoptopenjdk/openjdk8-openj9:alpine-slim
#openjdk:8-jre-alpine
RUN mkdir /opt/app
WORKDIR /opt/app
COPY digital-twins-location-rt.jar /opt/app/digital-twins.jar
CMD ["java", "-jar", "digital-twins.jar"]